# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ykdsg/my_workspace/MyCproject/network

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ykdsg/my_workspace/MyCproject/network

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ykdsg/my_workspace/MyCproject/network/CMakeFiles /Users/ykdsg/my_workspace/MyCproject/network//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ykdsg/my_workspace/MyCproject/network/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yolanda

# Build rule for target.
yolanda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yolanda
.PHONY : yolanda

# fast build rule for target.
yolanda/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/yolanda.dir/build.make lib/CMakeFiles/yolanda.dir/build
.PHONY : yolanda/fast

#=============================================================================
# Target rules for targets named make_socket

# Build rule for target.
make_socket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 make_socket
.PHONY : make_socket

# fast build rule for target.
make_socket/fast:
	$(MAKE) $(MAKESILENT) -f ch04/CMakeFiles/make_socket.dir/build.make ch04/CMakeFiles/make_socket.dir/build
.PHONY : make_socket/fast

#=============================================================================
# Target rules for targets named ch05.tcpServer

# Build rule for target.
ch05.tcpServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch05.tcpServer
.PHONY : ch05.tcpServer

# fast build rule for target.
ch05.tcpServer/fast:
	$(MAKE) $(MAKESILENT) -f ch05/CMakeFiles/ch05.tcpServer.dir/build.make ch05/CMakeFiles/ch05.tcpServer.dir/build
.PHONY : ch05.tcpServer/fast

#=============================================================================
# Target rules for targets named ch05.tcpClient

# Build rule for target.
ch05.tcpClient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch05.tcpClient
.PHONY : ch05.tcpClient

# fast build rule for target.
ch05.tcpClient/fast:
	$(MAKE) $(MAKESILENT) -f ch05/CMakeFiles/ch05.tcpClient.dir/build.make ch05/CMakeFiles/ch05.tcpClient.dir/build
.PHONY : ch05.tcpClient/fast

#=============================================================================
# Target rules for targets named ch05.demo

# Build rule for target.
ch05.demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch05.demo
.PHONY : ch05.demo

# fast build rule for target.
ch05.demo/fast:
	$(MAKE) $(MAKESILENT) -f ch05/CMakeFiles/ch05.demo.dir/build.make ch05/CMakeFiles/ch05.demo.dir/build
.PHONY : ch05.demo/fast

#=============================================================================
# Target rules for targets named udpserver

# Build rule for target.
udpserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 udpserver
.PHONY : udpserver

# fast build rule for target.
udpserver/fast:
	$(MAKE) $(MAKESILENT) -f ch06/CMakeFiles/udpserver.dir/build.make ch06/CMakeFiles/udpserver.dir/build
.PHONY : udpserver/fast

#=============================================================================
# Target rules for targets named udpclient

# Build rule for target.
udpclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 udpclient
.PHONY : udpclient

# fast build rule for target.
udpclient/fast:
	$(MAKE) $(MAKESILENT) -f ch06/CMakeFiles/udpclient.dir/build.make ch06/CMakeFiles/udpclient.dir/build
.PHONY : udpclient/fast

#=============================================================================
# Target rules for targets named ch07.unixstreamclient

# Build rule for target.
ch07.unixstreamclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch07.unixstreamclient
.PHONY : ch07.unixstreamclient

# fast build rule for target.
ch07.unixstreamclient/fast:
	$(MAKE) $(MAKESILENT) -f ch07/CMakeFiles/ch07.unixstreamclient.dir/build.make ch07/CMakeFiles/ch07.unixstreamclient.dir/build
.PHONY : ch07.unixstreamclient/fast

#=============================================================================
# Target rules for targets named ch07.unixdataclient

# Build rule for target.
ch07.unixdataclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch07.unixdataclient
.PHONY : ch07.unixdataclient

# fast build rule for target.
ch07.unixdataclient/fast:
	$(MAKE) $(MAKESILENT) -f ch07/CMakeFiles/ch07.unixdataclient.dir/build.make ch07/CMakeFiles/ch07.unixdataclient.dir/build
.PHONY : ch07.unixdataclient/fast

#=============================================================================
# Target rules for targets named ch07.unixdataserver

# Build rule for target.
ch07.unixdataserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch07.unixdataserver
.PHONY : ch07.unixdataserver

# fast build rule for target.
ch07.unixdataserver/fast:
	$(MAKE) $(MAKESILENT) -f ch07/CMakeFiles/ch07.unixdataserver.dir/build.make ch07/CMakeFiles/ch07.unixdataserver.dir/build
.PHONY : ch07.unixdataserver/fast

#=============================================================================
# Target rules for targets named ch07.unixstreamserver

# Build rule for target.
ch07.unixstreamserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch07.unixstreamserver
.PHONY : ch07.unixstreamserver

# fast build rule for target.
ch07.unixstreamserver/fast:
	$(MAKE) $(MAKESILENT) -f ch07/CMakeFiles/ch07.unixstreamserver.dir/build.make ch07/CMakeFiles/ch07.unixstreamserver.dir/build
.PHONY : ch07.unixstreamserver/fast

#=============================================================================
# Target rules for targets named ch11.graceserver.c

# Build rule for target.
ch11.graceserver.c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch11.graceserver.c
.PHONY : ch11.graceserver.c

# fast build rule for target.
ch11.graceserver.c/fast:
	$(MAKE) $(MAKESILENT) -f ch11/CMakeFiles/ch11.graceserver.c.dir/build.make ch11/CMakeFiles/ch11.graceserver.c.dir/build
.PHONY : ch11.graceserver.c/fast

#=============================================================================
# Target rules for targets named ch11.graceclient.c

# Build rule for target.
ch11.graceclient.c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch11.graceclient.c
.PHONY : ch11.graceclient.c

# fast build rule for target.
ch11.graceclient.c/fast:
	$(MAKE) $(MAKESILENT) -f ch11/CMakeFiles/ch11.graceclient.c.dir/build.make ch11/CMakeFiles/ch11.graceclient.c.dir/build
.PHONY : ch11.graceclient.c/fast

#=============================================================================
# Target rules for targets named ch12.pingserver

# Build rule for target.
ch12.pingserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch12.pingserver
.PHONY : ch12.pingserver

# fast build rule for target.
ch12.pingserver/fast:
	$(MAKE) $(MAKESILENT) -f ch12/CMakeFiles/ch12.pingserver.dir/build.make ch12/CMakeFiles/ch12.pingserver.dir/build
.PHONY : ch12.pingserver/fast

#=============================================================================
# Target rules for targets named ch12.pingclient

# Build rule for target.
ch12.pingclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch12.pingclient
.PHONY : ch12.pingclient

# fast build rule for target.
ch12.pingclient/fast:
	$(MAKE) $(MAKESILENT) -f ch12/CMakeFiles/ch12.pingclient.dir/build.make ch12/CMakeFiles/ch12.pingclient.dir/build
.PHONY : ch12.pingclient/fast

#=============================================================================
# Target rules for targets named ch13.tcpServer

# Build rule for target.
ch13.tcpServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch13.tcpServer
.PHONY : ch13.tcpServer

# fast build rule for target.
ch13.tcpServer/fast:
	$(MAKE) $(MAKESILENT) -f ch13/CMakeFiles/ch13.tcpServer.dir/build.make ch13/CMakeFiles/ch13.tcpServer.dir/build
.PHONY : ch13.tcpServer/fast

#=============================================================================
# Target rules for targets named ch13.batchwrite

# Build rule for target.
ch13.batchwrite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch13.batchwrite
.PHONY : ch13.batchwrite

# fast build rule for target.
ch13.batchwrite/fast:
	$(MAKE) $(MAKESILENT) -f ch13/CMakeFiles/ch13.batchwrite.dir/build.make ch13/CMakeFiles/ch13.batchwrite.dir/build
.PHONY : ch13.batchwrite/fast

#=============================================================================
# Target rules for targets named ch14.udpconnectclient

# Build rule for target.
ch14.udpconnectclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch14.udpconnectclient
.PHONY : ch14.udpconnectclient

# fast build rule for target.
ch14.udpconnectclient/fast:
	$(MAKE) $(MAKESILENT) -f ch14/CMakeFiles/ch14.udpconnectclient.dir/build.make ch14/CMakeFiles/ch14.udpconnectclient.dir/build
.PHONY : ch14.udpconnectclient/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ch05.demo"
	@echo "... ch05.tcpClient"
	@echo "... ch05.tcpServer"
	@echo "... ch07.unixdataclient"
	@echo "... ch07.unixdataserver"
	@echo "... ch07.unixstreamclient"
	@echo "... ch07.unixstreamserver"
	@echo "... ch11.graceclient.c"
	@echo "... ch11.graceserver.c"
	@echo "... ch12.pingclient"
	@echo "... ch12.pingserver"
	@echo "... ch13.batchwrite"
	@echo "... ch13.tcpServer"
	@echo "... ch14.udpconnectclient"
	@echo "... make_socket"
	@echo "... udpclient"
	@echo "... udpserver"
	@echo "... yolanda"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

